### ISSUE TITLE
Figure out RM Map format. (*.RMM)

### ISSUE THREAD

**Issue by cjschneider2** [cjschneider2/novluno#1]
There are various values in the RM Map format for which I have no idea what the values could be.
Namely, I have no idea how the tile format works. They are always 8 bytes long.
@briansteffens, You mentioned that you had some ideas about the format?

**Comment by briansteffens** [comment]
Still trying to sort the tiles out. So far I have (tentatively):

Bits 0-11 control overlaid objects (stuff like trees, houses)
Bit 12 seems to control both overlaid objects and the ground? Not sure on this one.
Bits 13-20 control the ground tile
Bits 21-30 control the ground tileset (a collection of tiles)
Bits 31-34 not sure
Bits 35-37 controls the cursor. All 0s is the normal cursor, anything else is a map change cursor
Bits 38-50 not sure
Bit 51 controls whether characters can walk on the left coordinate of the tile
Bit 52 not sure
Bit 53 controls whether characters can walk on the right coordinate of the tile
Bit 54 not sure
Bit 55-63 is more information controlling overlaid objects

What I'm struggling with most is figuring out how the ground tiles and overlaid object tiles map to the actual graphics files. I'm sort of wondering if there are hardcoded lookup tables somewhere in the client code, since I can't find any other pattern.

**Comment by cjschneider2** [comment]
Okay so I got into contact with the person who is doing the Redmoon2 Project and the order sort of goes like this: RMM Map files store tiles which hold (file_num, index) pairs for both the Objects and Tiles RMD files which are stored in the DATAs/{Obj, Tle}/*.rmd files. The RMD files are serialized objects which hold the information for the animations, tile offsets, and such, but also have which file & index is used for the sprites in the RLE files.

Have you looked at any of the RMD file formats?

**Comment by cjschneider2** [comment]
@briansteffens look at the  `documents/rm-formats.ods` document which I just pushed for the format of the RMM file that I have so far.

**Comment by cjschneider2** [comment]
I'm going to close this for now as I think we have a decent start to try to render a map.
