### ISSUE TITLE
Ingame message board

### ISSUE THREAD

**Issue by Chris4156** [cjschneider2/novluno#2]
Hello CJ,

Nice to see someone really investing in this game.
I am a professional webdesigner who has a TON of experience with RM.
I know the database inside and out and I have worked on many servers.
I know a lot of the server files aswell. I would be interested in joining you in this project.
And it would be fun to have a functioning message board ingame.
If you need any help or would like to contact me, send me an email at c.dedoncker@saron.net and I'll be sure to reply asap.

Chris

**Comment by jfield89** [comment]
If you still need any help. I'm interested and an avid learner. I have great understanding on how the server and game work together I have been experimenting with Redmoon ever since the files were released.

**Comment by cjschneider2** [comment]
Sure I'd love help. There are a few places where I'm going slow / stuck.
1. The first would be the server / client communication messages. If you have experience here or more versions of the server programs (if there is a version which is not compressed with aspack i'd love to hear it; Disassembling the server is painful otherwise.) I have developed a proxy program which will read out the packet data between the server & client, but there seems to be a hand-off from the login server to the map server(s) which somehow is made without giving an address over the connection so that's where I am there.
2. There are still some graphical bugs in the client with regards to the map tiles.
3. I Still haven't quite figured out how to put the animation data together, help here would be awesome, then I could actually add more (N)PC code.

If none of that tickles your fancy, I'd love to know what features or things you'd like to see. If you need help setting anything up I can update the documentation or help directly.

**Comment by jfield89** [comment]
I have multiple versions of the server files that i have gathered throughout the years, how could i tell if its compressed with aspack?

A few years ago I started teaching my self on trying to reverse engineer the redmoon files and I was using a couple of debuggers (IDAPro and OLYDBUG). Is this similar to what you are trying to do?

What is all needed to set up a rig to replicate what you have going on so i can do some digging on my end?

**Comment by cjschneider2** [comment]
It sort of depends on the type of packing program, but you'll usually know it because IDA spits out junk for function id's and there won't be any help with strings, usually strings will however usually identify the packer.

At the moment Rust would be the major requirement to run the programs. Otherwise SDL2 for the Client program and that should be it. Intellij / Clion with the rust plugin is a good IDE choice if you like)

I'd recommend getting rust through [rustup](https://rustup.rs). And SDL2, if you're on Linux download through your package manager.

For SDL2 on windows the easiest way is to move a copy of the sdl2 libs into rust's global libs folder. This would be located at (once you have rust installed) `%CARGO_HOME%.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib` (you can also switch stable for nightly if you need to use it). There _are_ more elegant ways to solve linking on windows involving build scripts, but this always works (aside from having to re-install it every language update).

In the `./server` folder is a program which is set to proxy a local connection and pass through and print out the packets to the rm-classic server. I have this running in a virtual XP machine so I don't have to mess network proxy's on my system.

in the `./client` folder is what I have so far with reading the maps and tiles and displaying them properly, it expects the redmoon files to be in `./data` folder when running from the base project directory. You can run any project from the root directory with a `cargo run -p client` command.

 Hopefully you can get started with that. Send me a mail at cjschneider2 @ gmail concerning the other files or more in depth problems.
